"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """$directory\
$git_state\
$git_branch\
$git_status\
$jobs\
$status\
$fill\
$cmake\
$container\
$docker_context\
$nodejs\
$kubernetes\
$gcloud\
$terraform
$character"""

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

[fill]
symbol = ' '

[directory]
truncate_to_repo = true
style = 'bold purple'
format = '[$path]($style)[$read_only]($read_only_style) '

[jobs]
number_threshold = 1
symbol = "󰒲 "

[git_branch]
style = 'bold yellow'

[git_status]
format = '([$conflicted$stashed$modified$staged$ahead_behind]($style) ) '
style = 'bold yellow'
up_to_date = '[](bold green)'
stashed = '󰀼 '
ahead = '[⇡${count}](bold green)'
behind = '[⇣${count}](bold red)'
diverged = '[⇡${ahead_count}](bold green)[⇣${behind_count}](bold red)'

[nodejs]
format = '[](bold purple)[$symbol($version)]($style)[](bold purple) '

[gcloud]
symbol = ' '
format = '[](bold purple)[$symbol $project]($style)[](bold purple) '

[kubernetes]
disabled = false
format = '[](bold purple)[$symbol$context( \($namespace\))]($style)[](bold purple) '

[[kubernetes.contexts]]
context_pattern = "\\w+_[\\w-]+_(?P<region>[\\w-]+)_(?P<cluster>[\\w-]+)"
context_alias = '$cluster $region'
