return {
    "EdenEast/nightfox.nvim",
    { "folke/tokyonight.nvim", branch = "main" },
    "mellow-theme/mellow.nvim",
    "lmburns/kimbox",
    "ramojus/mellifluous.nvim",
    "rebelot/kanagawa.nvim",
    "ribru17/bamboo.nvim",
    "tiagovla/tokyodark.nvim",
    "MyyPo/borrowed.nvim",
    "MisanthropicBit/warlock.nvim",
    "killitar/obscure.nvim",
    "qaptoR-nvim/chocolatier.nvim",
    "dgox16/oldworld.nvim",
    "yorumicolors/yorumi.nvim",
}
