return {
    "AlexvZyl/nordic.nvim",
    "EdenEast/nightfox.nvim",
    "askfiy/visual_studio_code",
    { "catppuccin/nvim", name = "catppuccin" },
    { "folke/tokyonight.nvim", branch = "main" },
    "hoprr/calvera-dark.nvim",
    "mellow-theme/mellow.nvim",
    "lmburns/kimbox",
    "projekt0n/caret.nvim",
    "ramojus/mellifluous.nvim",
    "rebelot/kanagawa.nvim",
    "ribru17/bamboo.nvim",
    "shaunsingh/moonlight.nvim",
    "tiagovla/tokyodark.nvim",
    "MyyPo/borrowed.nvim",
    { dir = "~/projects/nvim/warlock.nvim" },
}
