return {
    "AlexvZyl/nordic.nvim",
    "EdenEast/nightfox.nvim",
    "askfiy/visual_studio_code",
    { "folke/tokyonight.nvim", branch = "main" },
    "hoprr/calvera-dark.nvim",
    "mellow-theme/mellow.nvim",
    "lmburns/kimbox",
    "projekt0n/caret.nvim",
    "ramojus/mellifluous.nvim",
    "rebelot/kanagawa.nvim",
    "ribru17/bamboo.nvim",
    "tiagovla/tokyodark.nvim",
    "MyyPo/borrowed.nvim",
    "MisanthropicBit/warlock.nvim",
    "killitar/obscure.nvim",
    "qaptoR-nvim/chocolatier.nvim",
    "dgox16/oldworld.nvim",
    "yorumicolors/yorumi.nvim",
}
